name: Deploy Next.js to cPanel DEV Environment

on:
  push:
    branches:
      - develop  # Trigger deployment on 'develop' branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
  
      - name: Build and Export
        run: |
          npm run build

      - name: Set up SSH for cPanel
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Disable SSH host key checking to avoid fingerprint prompt
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Configure Git user
        run: |
          git config --global user.email "ge@niedrotech.com"
          git config --global user.name "Gem"

      - name: Push only the 'out' folder to cPanel Git repository
        run: |
          # Initialize Git repository
          git init
          
          # Add the cPanel Git repository as a remote
          git remote add cpanel ${{ secrets.CPANEL_DEV_REPO }}
          
          # Copy the content of the 'out' folder to the repo
          mkdir -p .deploy
          cp -r out/* .deploy/
          
          # Navigate to the deployment folder
          cd .deploy
          
          # Add the changes to git
          git add .
          git commit -m "Deploy Next.js build to DEV repo"
          
          # Push only the 'out' folder content to the cPanel repository
          git push cpanel -u master  # or 'main' if that's your default branch
